# Generated by Django 5.0.6 on 2024-07-01 16:19

import coffeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeapp', '0002_remove_user_id_products_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(db_index=True, null=True, unique=True, validators=[coffeapp.models.validate_phone_number]),
        ),
    ]
