# Generated by Django 5.0.6 on 2024-07-01 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeapp', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_orders',
            name='users_username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
