# Generated by Django 5.0.6 on 2024-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeapp', '0004_alter_users_orders_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='vertical',
            field=models.CharField(choices=[('CD', 'Cold Drinks'), ('CA', 'Cakes'), ('MS', 'Milkshakes'), ('HD', 'Hot Drinks')], db_index=True, max_length=2),
        ),
    ]
