# Generated by Django 5.0.6 on 2024-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeapp', '0007_alter_products_options_products_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='id',
        ),
        migrations.AlterField(
            model_name='storage',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(choices=[('sugar', 'sugar'), ('coffee', 'coffee'), ('flour', 'flour'), ('chocolate', 'chocolate')], max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
