# Generated by Django 5.0.6 on 2024-07-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeapp', '0009_cart_cartitem'),
        ('coffeapp', '0010_storage_chocolate_storage_coffee_storage_flour_and_more'),
    ]

    operations = [
    ]
